### ISSUE TITLE
Program gets stuck thinking there's no GPS

### ISSUE THREAD

**Issue by haarp** [flyingrub/SpeedMeter#11]
I've noticed this a few times now.  Sometimes the program thinks it has lost GPS, when it hasn't.

http://i.imgur.com/YkCSeUj.png

I just started it and pressed go. It had satellites, then suddenly jumped to 0 and claims to have lost the GPS fix, yet the accuracy keeps getting better (so obviously, there is a fix). It's stuck in this until I switch to another app and back.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/SpeedMeter/commit/6be6effc9adb69ff785dd1a321fa522d46971edd
should fix this. Please tell me if you have any update on this issue. :)
