### ISSUE TITLE
Miles per hour please

### ISSUE THREAD

**Issue by GReagle** [flyingrub/SpeedMeter#16]
All of the speed limit signs where I live are in miles per hour only.  Would it be possible to make SpeedMeter use miles per hour?

1 meter per second = 2.23693629 miles per hour so that would be the number to use in the code rather than 3.6.  It could be an option.

**Comment by GReagle** [comment]
I can program, but I've never worked on an Android app before.  I'll try to implement this myself.

**Comment by GReagle** [comment]
Why closed?

**Comment by GReagle** [comment]
I think I closed this issue by mistake.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/SpeedMeter/commit/62173d52af5a3de46de0620964fb97422ff90c31 fixed.
