### ISSUE TITLE
Bug :It show only Searching using 

### ISSUE THREAD

**Issue by jsroyal** [flyingrub/SpeedMeter#20]
I just setup my local system and build this project. I take worth dependency downloaded and I did successfully build gradle but in the app this show on nav bar and in the home page olny searching.

**Comment by jsroyal** [comment]
![screenshot_2016-11-28-02-27-14](https://cloud.githubusercontent.com/assets/10773353/20651863/76716dc2-b513-11e6-971c-6a69d766c2c4.png)

**Comment by flyingrub** [comment]
Could you try to get a gps fix first with google maps for exemple ?

**Comment by jsroyal** [comment]
@flyingrub Nope! There is I think not a network problem so have you thought about it? coz I had too long time but will check out later.

**Comment by flyingrub** [comment]
Dupliacte of #15
