### ISSUE TITLE
old F-Droid version

### ISSUE THREAD

**Issue by takiainen** [flyingrub/SpeedMeter#23]
Please update F-droid version if you got time, its from 2015! Many privacy concerned users don't have play store access.

**Comment by flyingrub** [comment]
It should be updated soon i rename the last tag so that it can be detected as an update automatically by fdroid.

**Comment by takiainen** [comment]
Thanks. And BTW, I really like this app! Good work.

**Comment by luckymedog** [comment]
miles still shows km (metric) mostly

**Comment by flyingrub** [comment]
What version do you have in the app settings ?

**Comment by luckymedog** [comment]
231

**Comment by flyingrub** [comment]
@luckymedog the version on f droid is now up to date. Feel free to open another issue related to your problem. :)
