### ISSUE TITLE
Tweak "use miles per hour" setting

### ISSUE THREAD

**Issue by rich123** [flyingrub/SpeedMeter#28]
F-Droid version 2.3.1.  The option "Use miles per hour" in settings really should be "Use Imperial measurements" instead.  Those of us in the US who continue to cling to our outdated imperial measurements for distances and speeds would also like to see the distance traveled, max speed, and average speed reported in imperial measurements as well.  Therefore the option "use miles per hour" in settings really should toggle all the distances/speeds to display in imperial measurements.  So this is really an "enhancement" request.  Thanks.

**Comment by andrewgaul** [comment]
See #25.

**Comment by rich123** [comment]
Ah, change already done - just waiting to merge the pull request.

**Comment by flyingrub** [comment]
wich is now done :)
