### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [flyingrub/SpeedMeter#29]
Hi @flyingrub 

I found [this app](https://play.google.com/store/apps/details?id=com.speedmeter.marcossitdev) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots and a link to this source code.

**Comment by flyingrub** [comment]
Thanks for reporting it @Poussinou ! 🥇
I filled a dmca request and pinged the guys on twitter.

**Comment by Poussinou** [comment]
@flyingrub There is another [here](https://play.google.com/store/apps/details?id=fly.speedmeter.cjc3), it's the older version of your app. Please report too :)

**Comment by flyingrub** [comment]
Both app are now deleted from the store :).
Thanks again @Poussinou :tada:

**Comment by Poussinou** [comment]
Great ! I'll report here if I find another one in the future
