### ISSUE TITLE
Current Speed not updated while stopped

### ISSUE THREAD

**Issue by haarp** [flyingrub/SpeedMeter#4]
I'm using v1.2.

When I was stopped, my speed should be 0km/h. Yet the app consistently showed 4km/h. The distance counter however was not incrementing so internally the program seemed to know that the speed was 0.

During this time, I had good GPS connectivity.

**Comment by flyingrub** [comment]
thanks for your interest, it motive me to update this app which need one since a long time. When i read the source code, i ask myself how could i did such horrible padding :p ...

i will look at all your issue and try to fix them, with an entire redisgn :)
