### ISSUE TITLE
Don't count stops towards time/average speed

### ISSUE THREAD

**Issue by haarp** [flyingrub/SpeedMeter#7]
When you're stopped (e.g. at a red light), the stop time should not count towards the average speed. This is usually how bike computers work. The time spent at red lights would otherwise unnecessarily decrease the average speed.

There should be two timers, 'time' and 'movement time'. 'Time' is always counting up, while 'Movement time' is only counting as long as speed > 0. 'Movement time' is then used to calculate the average speed. (It would probably be interesting to show both times on the screen tho)

This mode could be made optional and added to the (still empty) settings screen :)

**Comment by flyingrub** [comment]
fixed too.

**Comment by haarp** [comment]
Thank you very much for taking care of these issues! The new version is looking really beautiful and nicely minimalistic :)

I've requested that the version in Fdroid be upgraded too, so it should be available there shortly.

**Comment by flyingrub** [comment]
Yes i don't know why it didn't updated, it should detect that a new tag exist and build an new version automaticaly. I will look into it with the fdroid guys !)

**Comment by haarp** [comment]
That's what I meant, I've taken care of it :) It'll be updated  in Fdroid soon.

Oh, btw, I noticed one tiny thing in the new version that isn't worth opening a new issue for: http://i.imgur.com/kHbjINj.png
It appears that the Max speed label is offset to the left a tiiiiiiny bit :P

**Comment by flyingrub** [comment]
i saw it but i thought it was an optical illusion :p 
i will fix it when i will get my laptop back
