### ISSUE TITLE
Distance decimal point

### ISSUE THREAD

**Issue by haarp** [flyingrub/SpeedMeter#9]
After working around #8 by keeping the display on, Speedmeter seems to be working so far. And I'm loving the way it looks! There's one issue tho: http://i.imgur.com/O1DzLlr.png

Apparently I travelled 8830 km in less than an hour? But I'm no supersonic jet! :) This is probably supposed to be 8.830 km.

(While I'm here: It should be km, not Km. And why do the speeds get no decimal places?)

**Comment by flyingrub** [comment]
Yes, :0
And i see there is an issue with the refresh button, i don't have this one
here, but i'm on lolipop...

**Comment by haarp** [comment]
For the record, this is on Kitkat (Cyanogenmod 11 M12)

**Comment by haarp** [comment]
I just tried on Lollipop (CM12 nightly). The refresh button now renders properly, but the decimal point problem remains. It happens as soon as it switches to km.

**Comment by flyingrub** [comment]
should be fixed, let me know if it works for you :)

**Comment by haarp** [comment]
Thanks, I'll test it next time I'm on the go!

**Comment by haarp** [comment]
Tested, it's fixed, thanks!
